import Footer from "@/components/Footer";
import Head from "next/head";
import Homepage from "src/pages/sections/landing/Homepage";
import Pic from "src/pages/sections/landing/Pic";
import Second from "src/pages/sections/landing/Second";
import Testi from "src/pages/sections/landing/Testi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Golden Days</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Home */}
        <Homepage />
        {/* section 2 */}
        <Second />
        {/* section 3 */}
        <Pic />
        {/* section 4 */}
        <Testi />
        {/* <Reviewpage /> */}
        <Footer />
      </div>
    </>
  );
}
